import type { Metadata } from "next";
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import "./globals.css";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export const metadata: Metadata = {
  title: "Fan AI Land",
  description: "Generated by AMP",
};

export default async function RootLayout({
  children,
  params,
}: Props) {
  const { locale } = await params;

  // Middleware handles locale validation, so we can safely assume locale is valid here
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
